### ISSUE TITLE
cross compiled ds2 not executable on nexus 4 / samsung galaxy s4

### ISSUE THREAD

**Issue by mitp0sh** [facebook/ds2#4]
hey, 
just played around a bit with your ds2. i would love to see it working!!!
nevertheless on my nexus 4 it's not working...

i cross compiled ds2 on ubuntu 14.04, which was a bit of a hurdle ( the tutorial you wrote should be extended and mention that you also have to install bison and flex as well... ). after cross compiling was working, i copied ds2 binary to /data/local/tmp

when i try to execute it i get following strange error message:

/system/bin/sh: ./ds2: No such file or directory

i verified that that ds2 is located at /data/local/tmp/ds2 and right are set correctly:

-rwxrwxrwx shell    shell     1817889 2015-02-02 11:52 ds2

so either i'm missing something or there is some kind of problem here.

anyway, the project is great! keep on the good work.
looking forward to see a fix or help for my issue ;D

best regards,
mitp0sh

PS: Tested on a Samsung Galaxy S4 as well and have the same issue...

**Comment by sas** [comment]
Hey @mitp0sh, thanks for the note, I'll add the info about flex/bison to the documentation.

I need two things to understand what the problem is:
- What version of android do you have on your devices?
- Which instructions did you follow, the one for Linux-ARM?

You might wanna try this branch, which allows instructions specifically for android: https://github.com/sas/ds2/tree/android-build#cross-compiling-for-android

I need to make a few minor modifications to this branch and then I'll be able to merge it back to the main repository.
